# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QHeaderView,
    QListWidgetItem, QMainWindow, QProgressBar, QPushButton,
    QSizePolicy, QTabWidget, QTableWidget, QTableWidgetItem,
    QWidget)

from droplist import DropList

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1291, 752)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 1261, 721))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.grb_extract = QGroupBox(self.tab)
        self.grb_extract.setObjectName(u"grb_extract")
        self.grb_extract.setGeometry(QRect(730, 10, 351, 231))
        self.lst_extract = DropList(self.grb_extract)
        self.lst_extract.setObjectName(u"lst_extract")
        self.lst_extract.setGeometry(QRect(10, 30, 331, 151))
        self.btn_add_folder_extract = QPushButton(self.grb_extract)
        self.btn_add_folder_extract.setObjectName(u"btn_add_folder_extract")
        self.btn_add_folder_extract.setGeometry(QRect(260, 190, 80, 31))
        self.grb_stego = QGroupBox(self.tab)
        self.grb_stego.setObjectName(u"grb_stego")
        self.grb_stego.setGeometry(QRect(370, 10, 351, 231))
        self.lst_stego = DropList(self.grb_stego)
        self.lst_stego.setObjectName(u"lst_stego")
        self.lst_stego.setGeometry(QRect(10, 30, 331, 151))
        self.btn_add_folder_stego = QPushButton(self.grb_stego)
        self.btn_add_folder_stego.setObjectName(u"btn_add_folder_stego")
        self.btn_add_folder_stego.setGeometry(QRect(260, 190, 80, 31))
        self.grb_original = QGroupBox(self.tab)
        self.grb_original.setObjectName(u"grb_original")
        self.grb_original.setGeometry(QRect(10, 10, 351, 231))
        self.lst_original = DropList(self.grb_original)
        self.lst_original.setObjectName(u"lst_original")
        self.lst_original.setGeometry(QRect(10, 30, 331, 151))
        self.btn_add_folder_original = QPushButton(self.grb_original)
        self.btn_add_folder_original.setObjectName(u"btn_add_folder_original")
        self.btn_add_folder_original.setGeometry(QRect(260, 190, 80, 31))
        self.grb_text_metrics = QGroupBox(self.tab)
        self.grb_text_metrics.setObjectName(u"grb_text_metrics")
        self.grb_text_metrics.setGeometry(QRect(10, 260, 181, 341))
        self.chk_text_similarity = QCheckBox(self.grb_text_metrics)
        self.chk_text_similarity.setObjectName(u"chk_text_similarity")
        self.chk_text_similarity.setGeometry(QRect(10, 30, 91, 21))
        self.chk_text_levenshtein = QCheckBox(self.grb_text_metrics)
        self.chk_text_levenshtein.setObjectName(u"chk_text_levenshtein")
        self.chk_text_levenshtein.setGeometry(QRect(10, 60, 91, 21))
        self.chk_text_jaccard = QCheckBox(self.grb_text_metrics)
        self.chk_text_jaccard.setObjectName(u"chk_text_jaccard")
        self.chk_text_jaccard.setGeometry(QRect(10, 90, 81, 21))
        self.chk_text_exact_match = QCheckBox(self.grb_text_metrics)
        self.chk_text_exact_match.setObjectName(u"chk_text_exact_match")
        self.chk_text_exact_match.setGeometry(QRect(10, 120, 91, 21))
        self.chk_text_char_accuracy = QCheckBox(self.grb_text_metrics)
        self.chk_text_char_accuracy.setObjectName(u"chk_text_char_accuracy")
        self.chk_text_char_accuracy.setGeometry(QRect(10, 150, 101, 21))
        self.chk_text_bitwise_ber = QCheckBox(self.grb_text_metrics)
        self.chk_text_bitwise_ber.setObjectName(u"chk_text_bitwise_ber")
        self.chk_text_bitwise_ber.setGeometry(QRect(10, 180, 81, 21))
        self.grb_image_metrics = QGroupBox(self.tab)
        self.grb_image_metrics.setObjectName(u"grb_image_metrics")
        self.grb_image_metrics.setGeometry(QRect(410, 260, 181, 341))
        self.chk_image_mse = QCheckBox(self.grb_image_metrics)
        self.chk_image_mse.setObjectName(u"chk_image_mse")
        self.chk_image_mse.setGeometry(QRect(10, 30, 81, 21))
        self.chk_image_psnr = QCheckBox(self.grb_image_metrics)
        self.chk_image_psnr.setObjectName(u"chk_image_psnr")
        self.chk_image_psnr.setGeometry(QRect(10, 60, 71, 21))
        self.chk_image_ssim = QCheckBox(self.grb_image_metrics)
        self.chk_image_ssim.setObjectName(u"chk_image_ssim")
        self.chk_image_ssim.setGeometry(QRect(10, 90, 71, 21))
        self.chk_image_ber = QCheckBox(self.grb_image_metrics)
        self.chk_image_ber.setObjectName(u"chk_image_ber")
        self.chk_image_ber.setGeometry(QRect(10, 120, 71, 21))
        self.chk_image_dssim = QCheckBox(self.grb_image_metrics)
        self.chk_image_dssim.setObjectName(u"chk_image_dssim")
        self.chk_image_dssim.setGeometry(QRect(10, 150, 91, 21))
        self.chk_image_lpips = QCheckBox(self.grb_image_metrics)
        self.chk_image_lpips.setObjectName(u"chk_image_lpips")
        self.chk_image_lpips.setGeometry(QRect(10, 180, 91, 21))
        self.chk_image_bitwise_ber = QCheckBox(self.grb_image_metrics)
        self.chk_image_bitwise_ber.setObjectName(u"chk_image_bitwise_ber")
        self.chk_image_bitwise_ber.setGeometry(QRect(10, 210, 81, 21))
        self.chk_image_byte_accuracy = QCheckBox(self.grb_image_metrics)
        self.chk_image_byte_accuracy.setObjectName(u"chk_image_byte_accuracy")
        self.chk_image_byte_accuracy.setGeometry(QRect(10, 240, 101, 21))
        self.chk_image_exact_match = QCheckBox(self.grb_image_metrics)
        self.chk_image_exact_match.setObjectName(u"chk_image_exact_match")
        self.chk_image_exact_match.setGeometry(QRect(10, 270, 91, 21))
        self.chk_img_ai = QCheckBox(self.grb_image_metrics)
        self.chk_img_ai.setObjectName(u"chk_img_ai")
        self.chk_img_ai.setGeometry(QRect(10, 300, 151, 22))
        self.grb_audio_metrics = QGroupBox(self.tab)
        self.grb_audio_metrics.setObjectName(u"grb_audio_metrics")
        self.grb_audio_metrics.setGeometry(QRect(210, 260, 181, 341))
        self.chk_audio_mse = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_mse.setObjectName(u"chk_audio_mse")
        self.chk_audio_mse.setGeometry(QRect(10, 30, 81, 21))
        self.chk_audio_psnr = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_psnr.setObjectName(u"chk_audio_psnr")
        self.chk_audio_psnr.setGeometry(QRect(10, 90, 81, 21))
        self.chk_audio_snr = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_snr.setObjectName(u"chk_audio_snr")
        self.chk_audio_snr.setGeometry(QRect(10, 120, 81, 21))
        self.chk_audio_mae = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_mae.setObjectName(u"chk_audio_mae")
        self.chk_audio_mae.setGeometry(QRect(10, 60, 81, 21))
        self.chk_audio_lsd = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_lsd.setObjectName(u"chk_audio_lsd")
        self.chk_audio_lsd.setGeometry(QRect(10, 150, 81, 21))
        self.chk_audio_perceptual_score = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_perceptual_score.setObjectName(u"chk_audio_perceptual_score")
        self.chk_audio_perceptual_score.setGeometry(QRect(10, 180, 121, 21))
        self.chk_audio_bitwise_ber = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_bitwise_ber.setObjectName(u"chk_audio_bitwise_ber")
        self.chk_audio_bitwise_ber.setGeometry(QRect(10, 210, 121, 21))
        self.chk_audio_byte_accuracy = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_byte_accuracy.setObjectName(u"chk_audio_byte_accuracy")
        self.chk_audio_byte_accuracy.setGeometry(QRect(10, 240, 121, 21))
        self.chk_audio_exact_match = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_exact_match.setObjectName(u"chk_audio_exact_match")
        self.chk_audio_exact_match.setGeometry(QRect(10, 270, 121, 21))
        self.chk_aud_ai = QCheckBox(self.grb_audio_metrics)
        self.chk_aud_ai.setObjectName(u"chk_aud_ai")
        self.chk_aud_ai.setGeometry(QRect(10, 300, 151, 22))
        self.btn_generate_chart = QPushButton(self.tab)
        self.btn_generate_chart.setObjectName(u"btn_generate_chart")
        self.btn_generate_chart.setEnabled(False)
        self.btn_generate_chart.setGeometry(QRect(740, 280, 111, 41))
        self.btn_compute = QPushButton(self.tab)
        self.btn_compute.setObjectName(u"btn_compute")
        self.btn_compute.setGeometry(QRect(620, 280, 111, 41))
        self.progressBar = QProgressBar(self.tab)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(620, 330, 231, 21))
        self.progressBar.setValue(0)
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(1110, 10, 121, 151))
        self.btn_load_profile = QPushButton(self.groupBox)
        self.btn_load_profile.setObjectName(u"btn_load_profile")
        self.btn_load_profile.setGeometry(QRect(20, 40, 75, 31))
        self.btn_save_profile = QPushButton(self.groupBox)
        self.btn_save_profile.setObjectName(u"btn_save_profile")
        self.btn_save_profile.setGeometry(QRect(20, 90, 75, 31))
        self.btn_export_report = QPushButton(self.tab)
        self.btn_export_report.setObjectName(u"btn_export_report")
        self.btn_export_report.setGeometry(QRect(1120, 180, 101, 41))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tbl_results = QTableWidget(self.tab_2)
        self.tbl_results.setObjectName(u"tbl_results")
        self.tbl_results.setGeometry(QRect(10, 10, 1231, 661))
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"StegoTester", None))
        self.grb_extract.setTitle(QCoreApplication.translate("MainWindow", u"Extract", None))
        self.btn_add_folder_extract.setText(QCoreApplication.translate("MainWindow", u"Add Folder...", None))
        self.grb_stego.setTitle(QCoreApplication.translate("MainWindow", u"Stego", None))
        self.btn_add_folder_stego.setText(QCoreApplication.translate("MainWindow", u"Add Folder...", None))
        self.grb_original.setTitle(QCoreApplication.translate("MainWindow", u"Original", None))
        self.btn_add_folder_original.setText(QCoreApplication.translate("MainWindow", u"Add Folder...", None))
        self.grb_text_metrics.setTitle(QCoreApplication.translate("MainWindow", u"Text Metrics", None))
        self.chk_text_similarity.setText(QCoreApplication.translate("MainWindow", u"Similarity", None))
        self.chk_text_levenshtein.setText(QCoreApplication.translate("MainWindow", u"Levenshtein", None))
        self.chk_text_jaccard.setText(QCoreApplication.translate("MainWindow", u"Jaccard", None))
        self.chk_text_exact_match.setText(QCoreApplication.translate("MainWindow", u"exact_match", None))
        self.chk_text_char_accuracy.setText(QCoreApplication.translate("MainWindow", u"char_accuracy", None))
        self.chk_text_bitwise_ber.setText(QCoreApplication.translate("MainWindow", u"bitwise_ber", None))
        self.grb_image_metrics.setTitle(QCoreApplication.translate("MainWindow", u"Image Metrics", None))
        self.chk_image_mse.setText(QCoreApplication.translate("MainWindow", u"MSE", None))
        self.chk_image_psnr.setText(QCoreApplication.translate("MainWindow", u"PSNR", None))
        self.chk_image_ssim.setText(QCoreApplication.translate("MainWindow", u"SSIM", None))
        self.chk_image_ber.setText(QCoreApplication.translate("MainWindow", u"BER", None))
        self.chk_image_dssim.setText(QCoreApplication.translate("MainWindow", u"image_dssim", None))
        self.chk_image_lpips.setText(QCoreApplication.translate("MainWindow", u"image_lpips", None))
        self.chk_image_bitwise_ber.setText(QCoreApplication.translate("MainWindow", u"bitwise_ber", None))
        self.chk_image_byte_accuracy.setText(QCoreApplication.translate("MainWindow", u"byte_accuracy", None))
        self.chk_image_exact_match.setText(QCoreApplication.translate("MainWindow", u"exact_match", None))
        self.chk_img_ai.setText(QCoreApplication.translate("MainWindow", u"AI Detection (Diff Prob.)", None))
        self.grb_audio_metrics.setTitle(QCoreApplication.translate("MainWindow", u"Audio Metrics", None))
        self.chk_audio_mse.setText(QCoreApplication.translate("MainWindow", u"MSE", None))
        self.chk_audio_psnr.setText(QCoreApplication.translate("MainWindow", u"PSNR", None))
        self.chk_audio_snr.setText(QCoreApplication.translate("MainWindow", u"SNR", None))
        self.chk_audio_mae.setText(QCoreApplication.translate("MainWindow", u"MAE", None))
        self.chk_audio_lsd.setText(QCoreApplication.translate("MainWindow", u"LSD", None))
        self.chk_audio_perceptual_score.setText(QCoreApplication.translate("MainWindow", u"perceptual_score", None))
        self.chk_audio_bitwise_ber.setText(QCoreApplication.translate("MainWindow", u"bitwise_ber", None))
        self.chk_audio_byte_accuracy.setText(QCoreApplication.translate("MainWindow", u"byte_accuracy", None))
        self.chk_audio_exact_match.setText(QCoreApplication.translate("MainWindow", u"exact_match", None))
        self.chk_aud_ai.setText(QCoreApplication.translate("MainWindow", u"AI Detection (LSB Prob.)", None))
        self.btn_generate_chart.setText(QCoreApplication.translate("MainWindow", u"Generate Chart", None))
        self.btn_compute.setText(QCoreApplication.translate("MainWindow", u"Compute", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Profile", None))
        self.btn_load_profile.setText(QCoreApplication.translate("MainWindow", u"Load Profile", None))
        self.btn_save_profile.setText(QCoreApplication.translate("MainWindow", u"Save Profile", None))
        self.btn_export_report.setText(QCoreApplication.translate("MainWindow", u"Export Results...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Setup", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Results", None))
    # retranslateUi

