# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QHeaderView,
    QListWidgetItem, QMainWindow, QPushButton, QRadioButton,
    QSizePolicy, QTableWidget, QTableWidgetItem, QWidget)

from droplist import DropList

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1222, 628)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.grb_original = QGroupBox(self.centralwidget)
        self.grb_original.setObjectName(u"grb_original")
        self.grb_original.setGeometry(QRect(10, 20, 321, 141))
        self.lst_original = DropList(self.grb_original)
        self.lst_original.setObjectName(u"lst_original")
        self.lst_original.setGeometry(QRect(10, 20, 301, 111))
        self.grb_extract = QGroupBox(self.centralwidget)
        self.grb_extract.setObjectName(u"grb_extract")
        self.grb_extract.setGeometry(QRect(690, 20, 321, 141))
        self.lst_extract = DropList(self.grb_extract)
        self.lst_extract.setObjectName(u"lst_extract")
        self.lst_extract.setGeometry(QRect(10, 20, 301, 111))
        self.grb_stego = QGroupBox(self.centralwidget)
        self.grb_stego.setObjectName(u"grb_stego")
        self.grb_stego.setGeometry(QRect(350, 20, 321, 141))
        self.lst_stego = DropList(self.grb_stego)
        self.lst_stego.setObjectName(u"lst_stego")
        self.lst_stego.setGeometry(QRect(10, 20, 301, 111))
        self.grb_audio_metrics = QGroupBox(self.centralwidget)
        self.grb_audio_metrics.setObjectName(u"grb_audio_metrics")
        self.grb_audio_metrics.setGeometry(QRect(580, 170, 261, 141))
        self.chk_audio_mse = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_mse.setObjectName(u"chk_audio_mse")
        self.chk_audio_mse.setGeometry(QRect(10, 20, 81, 21))
        self.chk_audio_psnr = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_psnr.setObjectName(u"chk_audio_psnr")
        self.chk_audio_psnr.setGeometry(QRect(10, 80, 81, 21))
        self.chk_audio_snr = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_snr.setObjectName(u"chk_audio_snr")
        self.chk_audio_snr.setGeometry(QRect(10, 110, 81, 21))
        self.chk_audio_mae = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_mae.setObjectName(u"chk_audio_mae")
        self.chk_audio_mae.setGeometry(QRect(10, 50, 81, 21))
        self.chk_audio_lsd = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_lsd.setObjectName(u"chk_audio_lsd")
        self.chk_audio_lsd.setGeometry(QRect(80, 20, 81, 21))
        self.chk_audio_perceptual_score = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_perceptual_score.setObjectName(u"chk_audio_perceptual_score")
        self.chk_audio_perceptual_score.setGeometry(QRect(140, 20, 121, 21))
        self.chk_audio_bitwise_ber = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_bitwise_ber.setObjectName(u"chk_audio_bitwise_ber")
        self.chk_audio_bitwise_ber.setGeometry(QRect(140, 50, 121, 21))
        self.chk_audio_byte_accuracy = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_byte_accuracy.setObjectName(u"chk_audio_byte_accuracy")
        self.chk_audio_byte_accuracy.setGeometry(QRect(140, 80, 121, 21))
        self.chk_audio_exact_match = QCheckBox(self.grb_audio_metrics)
        self.chk_audio_exact_match.setObjectName(u"chk_audio_exact_match")
        self.chk_audio_exact_match.setGeometry(QRect(140, 110, 121, 21))
        self.grb_text_metrics = QGroupBox(self.centralwidget)
        self.grb_text_metrics.setObjectName(u"grb_text_metrics")
        self.grb_text_metrics.setGeometry(QRect(10, 170, 231, 141))
        self.chk_text_similarity = QCheckBox(self.grb_text_metrics)
        self.chk_text_similarity.setObjectName(u"chk_text_similarity")
        self.chk_text_similarity.setGeometry(QRect(10, 20, 91, 21))
        self.chk_text_levenshtein = QCheckBox(self.grb_text_metrics)
        self.chk_text_levenshtein.setObjectName(u"chk_text_levenshtein")
        self.chk_text_levenshtein.setGeometry(QRect(10, 50, 91, 21))
        self.chk_text_jaccard = QCheckBox(self.grb_text_metrics)
        self.chk_text_jaccard.setObjectName(u"chk_text_jaccard")
        self.chk_text_jaccard.setGeometry(QRect(10, 80, 81, 21))
        self.chk_text_exact_match = QCheckBox(self.grb_text_metrics)
        self.chk_text_exact_match.setObjectName(u"chk_text_exact_match")
        self.chk_text_exact_match.setGeometry(QRect(120, 20, 91, 21))
        self.chk_text_char_accuracy = QCheckBox(self.grb_text_metrics)
        self.chk_text_char_accuracy.setObjectName(u"chk_text_char_accuracy")
        self.chk_text_char_accuracy.setGeometry(QRect(120, 50, 101, 21))
        self.chk_text_bitwise_ber = QCheckBox(self.grb_text_metrics)
        self.chk_text_bitwise_ber.setObjectName(u"chk_text_bitwise_ber")
        self.chk_text_bitwise_ber.setGeometry(QRect(120, 80, 81, 21))
        self.grb_image_metrics = QGroupBox(self.centralwidget)
        self.grb_image_metrics.setObjectName(u"grb_image_metrics")
        self.grb_image_metrics.setGeometry(QRect(270, 170, 281, 141))
        self.chk_image_mse = QCheckBox(self.grb_image_metrics)
        self.chk_image_mse.setObjectName(u"chk_image_mse")
        self.chk_image_mse.setGeometry(QRect(10, 20, 81, 21))
        self.chk_image_psnr = QCheckBox(self.grb_image_metrics)
        self.chk_image_psnr.setObjectName(u"chk_image_psnr")
        self.chk_image_psnr.setGeometry(QRect(10, 50, 71, 21))
        self.chk_image_ssim = QCheckBox(self.grb_image_metrics)
        self.chk_image_ssim.setObjectName(u"chk_image_ssim")
        self.chk_image_ssim.setGeometry(QRect(10, 80, 71, 21))
        self.chk_image_ber = QCheckBox(self.grb_image_metrics)
        self.chk_image_ber.setObjectName(u"chk_image_ber")
        self.chk_image_ber.setGeometry(QRect(10, 110, 71, 21))
        self.chk_image_dssim = QCheckBox(self.grb_image_metrics)
        self.chk_image_dssim.setObjectName(u"chk_image_dssim")
        self.chk_image_dssim.setGeometry(QRect(70, 20, 91, 21))
        self.chk_image_lpips = QCheckBox(self.grb_image_metrics)
        self.chk_image_lpips.setObjectName(u"chk_image_lpips")
        self.chk_image_lpips.setGeometry(QRect(70, 50, 91, 21))
        self.chk_image_bitwise_ber = QCheckBox(self.grb_image_metrics)
        self.chk_image_bitwise_ber.setObjectName(u"chk_image_bitwise_ber")
        self.chk_image_bitwise_ber.setGeometry(QRect(170, 20, 81, 21))
        self.chk_image_byte_accuracy = QCheckBox(self.grb_image_metrics)
        self.chk_image_byte_accuracy.setObjectName(u"chk_image_byte_accuracy")
        self.chk_image_byte_accuracy.setGeometry(QRect(170, 50, 101, 21))
        self.chk_image_exact_match = QCheckBox(self.grb_image_metrics)
        self.chk_image_exact_match.setObjectName(u"chk_image_exact_match")
        self.chk_image_exact_match.setGeometry(QRect(170, 80, 91, 21))
        self.grb_export_format = QGroupBox(self.centralwidget)
        self.grb_export_format.setObjectName(u"grb_export_format")
        self.grb_export_format.setGeometry(QRect(1030, 20, 171, 141))
        self.btn_export_report = QPushButton(self.grb_export_format)
        self.btn_export_report.setObjectName(u"btn_export_report")
        self.btn_export_report.setGeometry(QRect(10, 90, 111, 31))
        self.rdb_export_txt = QRadioButton(self.grb_export_format)
        self.rdb_export_txt.setObjectName(u"rdb_export_txt")
        self.rdb_export_txt.setGeometry(QRect(10, 30, 111, 21))
        self.rdb_export_pdf = QRadioButton(self.grb_export_format)
        self.rdb_export_pdf.setObjectName(u"rdb_export_pdf")
        self.rdb_export_pdf.setGeometry(QRect(10, 60, 89, 21))
        self.grb_results = QGroupBox(self.centralwidget)
        self.grb_results.setObjectName(u"grb_results")
        self.grb_results.setGeometry(QRect(10, 320, 1201, 291))
        self.tbl_results = QTableWidget(self.grb_results)
        self.tbl_results.setObjectName(u"tbl_results")
        self.tbl_results.setGeometry(QRect(10, 20, 1181, 261))
        self.btn_compute = QPushButton(self.centralwidget)
        self.btn_compute.setObjectName(u"btn_compute")
        self.btn_compute.setGeometry(QRect(1050, 180, 111, 41))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"StegoTester", None))
        self.grb_original.setTitle(QCoreApplication.translate("MainWindow", u"Original", None))
        self.grb_extract.setTitle(QCoreApplication.translate("MainWindow", u"Extract", None))
        self.grb_stego.setTitle(QCoreApplication.translate("MainWindow", u"Stego", None))
        self.grb_audio_metrics.setTitle(QCoreApplication.translate("MainWindow", u"Audio Metrics", None))
        self.chk_audio_mse.setText(QCoreApplication.translate("MainWindow", u"MSE", None))
        self.chk_audio_psnr.setText(QCoreApplication.translate("MainWindow", u"PSNR", None))
        self.chk_audio_snr.setText(QCoreApplication.translate("MainWindow", u"SNR", None))
        self.chk_audio_mae.setText(QCoreApplication.translate("MainWindow", u"MAE", None))
        self.chk_audio_lsd.setText(QCoreApplication.translate("MainWindow", u"LSD", None))
        self.chk_audio_perceptual_score.setText(QCoreApplication.translate("MainWindow", u"perceptual_score", None))
        self.chk_audio_bitwise_ber.setText(QCoreApplication.translate("MainWindow", u"bitwise_ber", None))
        self.chk_audio_byte_accuracy.setText(QCoreApplication.translate("MainWindow", u"byte_accuracy", None))
        self.chk_audio_exact_match.setText(QCoreApplication.translate("MainWindow", u"exact_match", None))
        self.grb_text_metrics.setTitle(QCoreApplication.translate("MainWindow", u"Text Metrics", None))
        self.chk_text_similarity.setText(QCoreApplication.translate("MainWindow", u"Similarity", None))
        self.chk_text_levenshtein.setText(QCoreApplication.translate("MainWindow", u"Levenshtein", None))
        self.chk_text_jaccard.setText(QCoreApplication.translate("MainWindow", u"Jaccard", None))
        self.chk_text_exact_match.setText(QCoreApplication.translate("MainWindow", u"exact_match", None))
        self.chk_text_char_accuracy.setText(QCoreApplication.translate("MainWindow", u"char_accuracy", None))
        self.chk_text_bitwise_ber.setText(QCoreApplication.translate("MainWindow", u"bitwise_ber", None))
        self.grb_image_metrics.setTitle(QCoreApplication.translate("MainWindow", u"Image Metrics", None))
        self.chk_image_mse.setText(QCoreApplication.translate("MainWindow", u"MSE", None))
        self.chk_image_psnr.setText(QCoreApplication.translate("MainWindow", u"PSNR", None))
        self.chk_image_ssim.setText(QCoreApplication.translate("MainWindow", u"SSIM", None))
        self.chk_image_ber.setText(QCoreApplication.translate("MainWindow", u"BER", None))
        self.chk_image_dssim.setText(QCoreApplication.translate("MainWindow", u"image_dssim", None))
        self.chk_image_lpips.setText(QCoreApplication.translate("MainWindow", u"image_lpips", None))
        self.chk_image_bitwise_ber.setText(QCoreApplication.translate("MainWindow", u"bitwise_ber", None))
        self.chk_image_byte_accuracy.setText(QCoreApplication.translate("MainWindow", u"byte_accuracy", None))
        self.chk_image_exact_match.setText(QCoreApplication.translate("MainWindow", u"exact_match", None))
        self.grb_export_format.setTitle(QCoreApplication.translate("MainWindow", u"Export format", None))
        self.btn_export_report.setText(QCoreApplication.translate("MainWindow", u"Export Reports", None))
        self.rdb_export_txt.setText(QCoreApplication.translate("MainWindow", u"Text Report (.txt)", None))
        self.rdb_export_pdf.setText(QCoreApplication.translate("MainWindow", u"PDF (.pdf)", None))
        self.grb_results.setTitle(QCoreApplication.translate("MainWindow", u"Results", None))
        self.btn_compute.setText(QCoreApplication.translate("MainWindow", u"Compute", None))
    # retranslateUi

